#!/usr/bin/env bash

function run() {
    if ! pgrep -f "$1"; then
        "$@" &
    fi
}

run "/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1"
run "steam"
run "feh" --no-fehbg --randomize --recursive --bg-fill ~/.junk/xdg/Pictures/Wallpapers/
run "vesktop"
